services:
  app:
    build:
      tags:
        - pd-compose:latest
    image: pd-compose:latest
    container_name: pd-compose
    command: tail -f /dev/null
    volumes:
      - .:/data/data/com.termux/files/home/pd-compose
    stdin_open: true
    tty: true
